/* Generated by timer/build.py from the debate-prep format library. Do not edit by hand. */
/* Sources: recruit-1v1.md, recruit-2v2.md, recruit-3v3.md, ustc-freshman-cup.md, ustc-school-cup-2025.md */
(function (DT) {
  'use strict';
  DT.BUILTIN_FORMATS = [
  {
    "id": "recruit-1v1",
    "name": "招新赛 1v1",
    "builtin": true,
    "source": "recruit-1v1.md",
    "theme": "hall",
    "bells": {
      "warn": [
        30
      ],
      "countdown": 0,
      "end": "double"
    },
    "stages": [
      {
        "id": "recruit-1v1-1",
        "name": "正方一辩立论",
        "secs": 180,
        "type": "single",
        "side": "pro",
        "speaker": "正一",
        "block": "A"
      },
      {
        "id": "recruit-1v1-2",
        "name": "反方一辩质询正方一辩",
        "secs": 120,
        "type": "single",
        "side": "con",
        "speaker": "反一 问，正一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-1v1-3",
        "name": "反方一辩立论",
        "secs": 180,
        "type": "single",
        "side": "con",
        "speaker": "反一",
        "block": "A"
      },
      {
        "id": "recruit-1v1-4",
        "name": "正方一辩质询反方一辩",
        "secs": 120,
        "type": "single",
        "side": "pro",
        "speaker": "正一 问，反一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-1v1-b1",
        "name": "中场休息",
        "secs": 60,
        "type": "break",
        "side": null
      },
      {
        "id": "recruit-1v1-5",
        "name": "正反双方一辩对辩",
        "secs": 120,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "正一 与 反一",
        "block": "B",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "recruit-1v1-b2",
        "name": "中场休息",
        "secs": 60,
        "type": "break",
        "side": null
      },
      {
        "id": "recruit-1v1-6",
        "name": "反方一辩结辩",
        "secs": 120,
        "type": "single",
        "side": "con",
        "speaker": "反一",
        "block": "C"
      },
      {
        "id": "recruit-1v1-7",
        "name": "正方一辩结辩",
        "secs": 120,
        "type": "single",
        "side": "pro",
        "speaker": "正一",
        "block": "C"
      }
    ],
    "extras": []
  },
  {
    "id": "recruit-2v2",
    "name": "招新赛 2v2",
    "builtin": true,
    "source": "recruit-2v2.md",
    "theme": "hall",
    "bells": {
      "warn": [
        30
      ],
      "countdown": 0,
      "end": "double"
    },
    "stages": [
      {
        "id": "recruit-2v2-1",
        "name": "正方一辩立论",
        "secs": 180,
        "type": "single",
        "side": "pro",
        "speaker": "正一",
        "block": "A"
      },
      {
        "id": "recruit-2v2-2",
        "name": "反方二辩质询正方一辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反二 问，正一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-2v2-3",
        "name": "反方一辩立论",
        "secs": 180,
        "type": "single",
        "side": "con",
        "speaker": "反一",
        "block": "A"
      },
      {
        "id": "recruit-2v2-4",
        "name": "正方二辩质询反方一辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正二 问，反一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-2v2-b1",
        "name": "中场休息",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "recruit-2v2-5",
        "name": "正反双方一辩对辩",
        "secs": 90,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "正一 与 反一",
        "block": "B",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "recruit-2v2-6",
        "name": "反方二辩申论",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反二",
        "block": "B"
      },
      {
        "id": "recruit-2v2-7",
        "name": "正方一辩质询反方二辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正一 问，反二 答",
        "block": "B",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-2v2-8",
        "name": "正方二辩申论",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正二",
        "block": "B"
      },
      {
        "id": "recruit-2v2-9",
        "name": "反方一辩质询正方二辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反一 问，正二 答",
        "block": "B",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-2v2-b2",
        "name": "中场休息",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "recruit-2v2-10",
        "name": "正反双方二辩对辩",
        "secs": 90,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "正二 与 反二",
        "block": "C",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "recruit-2v2-11",
        "name": "反方一辩结辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反一",
        "block": "C"
      },
      {
        "id": "recruit-2v2-12",
        "name": "正方一辩结辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正一",
        "block": "C"
      }
    ],
    "extras": []
  },
  {
    "id": "recruit-3v3",
    "name": "招新赛 3v3",
    "builtin": true,
    "source": "recruit-3v3.md",
    "theme": "hall",
    "bells": {
      "warn": [
        30
      ],
      "countdown": 0,
      "end": "double"
    },
    "stages": [
      {
        "id": "recruit-3v3-1",
        "name": "正方一辩立论",
        "secs": 180,
        "type": "single",
        "side": "pro",
        "speaker": "正一",
        "block": "A"
      },
      {
        "id": "recruit-3v3-2",
        "name": "反方二辩质询正方一辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反二 问，正一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-3v3-3",
        "name": "反方一辩立论",
        "secs": 180,
        "type": "single",
        "side": "con",
        "speaker": "反一",
        "block": "A"
      },
      {
        "id": "recruit-3v3-4",
        "name": "正方二辩质询反方一辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正二 问，反一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-3v3-b1",
        "name": "中场休息",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "recruit-3v3-5",
        "name": "正反双方三辩对辩",
        "secs": 90,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "正三 与 反三",
        "block": "B",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "recruit-3v3-6",
        "name": "反方二辩申论",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反二",
        "block": "B"
      },
      {
        "id": "recruit-3v3-7",
        "name": "正方三辩质询反方二辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正三 问，反二 答",
        "block": "B",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-3v3-8",
        "name": "正方二辩申论",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正二",
        "block": "B"
      },
      {
        "id": "recruit-3v3-9",
        "name": "反方三辩质询正方二辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反三 问，正二 答",
        "block": "B",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-3v3-b2",
        "name": "中场休息",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "recruit-3v3-10",
        "name": "正反双方一辩对辩",
        "secs": 90,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "正一 与 反一",
        "block": "C",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "recruit-3v3-11",
        "name": "正方三辩申论",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正三",
        "block": "C"
      },
      {
        "id": "recruit-3v3-12",
        "name": "反方一辩质询正方三辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反一 问，正三 答",
        "block": "C",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-3v3-13",
        "name": "反方三辩申论",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反三",
        "block": "C"
      },
      {
        "id": "recruit-3v3-14",
        "name": "正方一辩质询反方三辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正一 问，反三 答",
        "block": "C",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "recruit-3v3-b3",
        "name": "中场休息",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "recruit-3v3-15",
        "name": "正反双方二辩对辩",
        "secs": 90,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "正二 与 反二",
        "block": "D",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "recruit-3v3-16",
        "name": "反方一辩结辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反一",
        "block": "D"
      },
      {
        "id": "recruit-3v3-17",
        "name": "正方一辩结辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正一",
        "block": "D"
      }
    ],
    "extras": []
  },
  {
    "id": "ustc-freshman-cup",
    "name": "中国科学技术大学新生辩论赛",
    "builtin": true,
    "source": "ustc-freshman-cup.md",
    "theme": "hall",
    "bells": {
      "warn": [
        30
      ],
      "countdown": 0,
      "end": "double"
    },
    "stages": [
      {
        "id": "ustc-freshman-cup-1",
        "name": "正方一辩开篇立论",
        "secs": 180,
        "type": "single",
        "side": "pro",
        "speaker": "正一",
        "block": "A"
      },
      {
        "id": "ustc-freshman-cup-2",
        "name": "反方四辩质询正方一辩",
        "secs": 120,
        "type": "single",
        "side": "con",
        "speaker": "反四 问，正一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "ustc-freshman-cup-3",
        "name": "反方一辩开篇立论",
        "secs": 180,
        "type": "single",
        "side": "con",
        "speaker": "反一",
        "block": "A"
      },
      {
        "id": "ustc-freshman-cup-4",
        "name": "正方四辩质询反方一辩",
        "secs": 120,
        "type": "single",
        "side": "pro",
        "speaker": "正四 问，反一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "ustc-freshman-cup-5",
        "name": "评委打分",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "ustc-freshman-cup-6",
        "name": "反方二辩驳论",
        "secs": 120,
        "type": "single",
        "side": "con",
        "speaker": "反二",
        "block": "B"
      },
      {
        "id": "ustc-freshman-cup-7",
        "name": "正方二辩驳论",
        "secs": 120,
        "type": "single",
        "side": "pro",
        "speaker": "正二",
        "block": "B"
      },
      {
        "id": "ustc-freshman-cup-8",
        "name": "正反方二辩对辩",
        "secs": 90,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "正二 与 反二",
        "block": "B",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "ustc-freshman-cup-9",
        "name": "评委打分",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "ustc-freshman-cup-10",
        "name": "正方三辩盘问反方二辩、四辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正三 问，反二/反四 答",
        "block": "C",
        "note": "单边计时：只计盘问方，对方回答时按 P 暂停"
      },
      {
        "id": "ustc-freshman-cup-11",
        "name": "反方三辩盘问正方二辩、四辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反三 问，正二/正四 答",
        "block": "C",
        "note": "单边计时：只计盘问方，对方回答时按 P 暂停"
      },
      {
        "id": "ustc-freshman-cup-12",
        "name": "正方三辩盘问小结",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正三",
        "block": "C"
      },
      {
        "id": "ustc-freshman-cup-13",
        "name": "反方三辩盘问小结",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反三",
        "block": "C"
      },
      {
        "id": "ustc-freshman-cup-14",
        "name": "评委打分",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "ustc-freshman-cup-15",
        "name": "自由辩论",
        "secs": 240,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "全员",
        "block": "D",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "ustc-freshman-cup-16",
        "name": "评委打分",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "ustc-freshman-cup-17",
        "name": "反方四辩结辩",
        "secs": 210,
        "type": "single",
        "side": "con",
        "speaker": "反四",
        "block": "E"
      },
      {
        "id": "ustc-freshman-cup-18",
        "name": "正方四辩结辩",
        "secs": 210,
        "type": "single",
        "side": "pro",
        "speaker": "正四",
        "block": "E"
      }
    ],
    "extras": []
  },
  {
    "id": "ustc-school-cup-2025",
    "name": "2025 年中国科学技术大学校赛",
    "builtin": true,
    "source": "ustc-school-cup-2025.md",
    "theme": "hall",
    "bells": {
      "warn": [
        30
      ],
      "countdown": 0,
      "end": "double"
    },
    "stages": [
      {
        "id": "ustc-school-cup-2025-1",
        "name": "正方一辩开篇立论",
        "secs": 180,
        "type": "single",
        "side": "pro",
        "speaker": "正一",
        "block": "A"
      },
      {
        "id": "ustc-school-cup-2025-2",
        "name": "反方二辩质询正方一辩",
        "secs": 120,
        "type": "single",
        "side": "con",
        "speaker": "反二 问，正一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "ustc-school-cup-2025-3",
        "name": "反方一辩开篇立论",
        "secs": 180,
        "type": "single",
        "side": "con",
        "speaker": "反一",
        "block": "A"
      },
      {
        "id": "ustc-school-cup-2025-4",
        "name": "正方二辩质询反方一辩",
        "secs": 120,
        "type": "single",
        "side": "pro",
        "speaker": "正二 问，反一 答",
        "block": "A",
        "note": "双边计时：问答共用这一个表"
      },
      {
        "id": "ustc-school-cup-2025-5",
        "name": "评委打分",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "ustc-school-cup-2025-6",
        "name": "反方二辩驳论",
        "secs": 120,
        "type": "single",
        "side": "con",
        "speaker": "反二",
        "block": "B"
      },
      {
        "id": "ustc-school-cup-2025-7",
        "name": "正方二辩驳论",
        "secs": 120,
        "type": "single",
        "side": "pro",
        "speaker": "正二",
        "block": "B"
      },
      {
        "id": "ustc-school-cup-2025-8",
        "name": "正反方四辩对辩",
        "secs": 90,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "正四 与 反四",
        "block": "B",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "ustc-school-cup-2025-9",
        "name": "评委打分",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "ustc-school-cup-2025-10",
        "name": "正方三辩盘问反方二辩、四辩",
        "secs": 90,
        "type": "single",
        "side": "pro",
        "speaker": "正三 问",
        "block": "C",
        "note": "单边计时：只计盘问方，对方回答时按 P 暂停"
      },
      {
        "id": "ustc-school-cup-2025-11",
        "name": "反方三辩盘问正方二辩、四辩",
        "secs": 90,
        "type": "single",
        "side": "con",
        "speaker": "反三 问",
        "block": "C",
        "note": "单边计时：只计盘问方，对方回答时按 P 暂停"
      },
      {
        "id": "ustc-school-cup-2025-12",
        "name": "正方三辩盘问小结",
        "secs": 120,
        "type": "single",
        "side": "pro",
        "speaker": "正三",
        "block": "C"
      },
      {
        "id": "ustc-school-cup-2025-13",
        "name": "反方三辩盘问小结",
        "secs": 120,
        "type": "single",
        "side": "con",
        "speaker": "反三",
        "block": "C"
      },
      {
        "id": "ustc-school-cup-2025-14",
        "name": "评委打分",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "ustc-school-cup-2025-15",
        "name": "自由辩论",
        "secs": 240,
        "type": "dual",
        "side": null,
        "first": "pro",
        "speaker": "全员",
        "block": "D",
        "note": "A 给正方、L 给反方；一方用完自动转给对方"
      },
      {
        "id": "ustc-school-cup-2025-16",
        "name": "评委打分",
        "secs": 30,
        "type": "break",
        "side": null
      },
      {
        "id": "ustc-school-cup-2025-17",
        "name": "反方四辩结辩",
        "secs": 210,
        "type": "single",
        "side": "con",
        "speaker": "反四",
        "block": "E"
      },
      {
        "id": "ustc-school-cup-2025-18",
        "name": "正方四辩结辩",
        "secs": 210,
        "type": "single",
        "side": "pro",
        "speaker": "正四",
        "block": "E"
      }
    ],
    "extras": [
      {
        "group": "奇袭",
        "perSide": 1,
        "variants": [
          {
            "name": "奇袭质询",
            "type": "single",
            "secs": 150,
            "note": "双边计时：问答共用这一个表"
          },
          {
            "name": "奇袭申论",
            "type": "single",
            "secs": 120
          }
        ]
      }
    ]
  }
];
})(window.DT = window.DT || {});
